#!/bin/bash

echo "📦 Certificate Export Helper"
echo "=========================="
echo ""
echo "1. ダウンロードした証明書(.cer)をダブルクリックしてキーチェーンに追加"
echo "2. キーチェーンアクセスを開く"
echo "3. 「証明書」カテゴリで「Developer ID Application: [Your Name]」を探す"
echo "4. 証明書を右クリック → 「書き出す」"
echo "5. フォーマット: 個人情報交換(.p12)"
echo "6. パスワードを設定（覚えておく！）"
echo ""
echo "証明書を書き出したら、以下のコマンドを実行："
echo ""
echo "# 証明書をbase64に変換"
echo "base64 -i ~/Desktop/Certificates.p12 -o certificate_base64.txt"
echo ""
echo "# Team IDを確認"
echo "security find-identity -v -p codesigning | grep 'Developer ID Application'"
echo ""
echo "括弧内の10文字の英数字がTeam IDです（例: (ABCDE12345)）"